/* @jest-environment node */

const localStorageMock = { getItem: jest.fn(), setItem: jest.fn(), clear: jest.fn(), removeItem: jest.fn() };
const documentMock = { getElementById: jest.fn(), createElement: jest.fn() };
const globalMock = { document: documentMock, localStorage: localStorageMock, console: { warn: jest.fn() } };

describe('TodoApp', () => {
  let app;

  beforeEach(() => {
    const mockElements = {
      todoInput: { value: '', addEventListener: jest.fn(), dispatchEvent: jest.fn() },
      addBtn: { addEventListener: jest.fn(), disabled: false },
      todoList: { innerHTML: '' },
      itemCount: { textContent: '' },
      emptyState: {}
    };
    documentMock.getElementById.mockImplementation(id => mockElements[id] || mockElements.emptyState);
    documentMock.createElement.mockReturnValue({ textContent: '', innerHTML: '' });
    localStorageMock.getItem.mockReturnValue(null);
    localStorageMock.setItem.mockClear();
  });

  test('initializes with empty state', () => {
    class TodoApp { constructor() { this.todos = this.loadTodos(); this.todoInput = globalMock.document.getElementById('todoInput'); this.addBtn = globalMock.document.getElementById('addBtn'); this.todoList = globalMock.document.getElementById('todoList'); this.itemCount = globalMock.document.getElementById('itemCount'); this.emptyState = globalMock.document.getElementById('emptyState'); this.init(); } init() { this.addBtn.addEventListener('click', () => this.addTodo()); this.todoInput.addEventListener('keypress', (e) => { if (e.key === 'Enter') this.addTodo(); }); this.todoInput.addEventListener('input', () => this.updateAddButton()); this.render(); this.updateAddButton(); } addTodo() { const text = this.todoInput.value.trim(); if (!text) return; const todo = { id: Date.now() + Math.random(), text: text, completed: false, createdAt: new Date().toISOString() }; this.todos.push(todo); this.todoInput.value = ''; this.saveTodos(); this.render(); this.updateAddButton(); } toggleTodo(id) { const todo = this.todos.find(t => t.id === id); if (todo) { todo.completed = !todo.completed; this.saveTodos(); this.render(); } } deleteTodo(id) { this.todos = this.todos.filter(t => t.id !== id); this.saveTodos(); this.render(); } updateAddButton() { const hasText = this.todoInput.value.trim().length > 0; this.addBtn.disabled = !hasText; } render() { this.renderTodos(); this.updateItemCount(); } renderTodos() { if (this.todos.length === 0) { this.todoList.innerHTML = '<div class="empty-state">No todos yet. Add one above!</div>'; return; } const todosHtml = this.todos.map(todo => `<div class="todo-item ${todo.completed ? 'completed' : ''}"><input type="checkbox" class="todo-checkbox" ${todo.completed ? 'checked' : ''} onchange="app.toggleTodo(${todo.id})"><span class="todo-text">${this.escapeHtml(todo.text)}</span><button class="delete-btn" onclick="app.deleteTodo(${todo.id})">Delete</button></div>`).join(''); this.todoList.innerHTML = todosHtml; } updateItemCount() { const remaining = this.todos.filter(t => !t.completed).length; const total = this.todos.length; if (total === 0) { this.itemCount.textContent = 'No items'; } else if (remaining === 0) { this.itemCount.textContent = 'All items completed! 🎉'; } else { this.itemCount.textContent = `${remaining} item${remaining !== 1 ? 's' : ''} remaining`; } } escapeHtml(text) { const div = globalMock.document.createElement('div'); div.textContent = text; return div.innerHTML; } saveTodos() { try { globalMock.localStorage.setItem('todos', JSON.stringify(this.todos)); } catch (e) { globalMock.console.warn('Could not save todos to localStorage:', e); } } loadTodos() { try { const stored = globalMock.localStorage.getItem('todos'); return stored ? JSON.parse(stored) : []; } catch (e) { globalMock.console.warn('Could not load todos from localStorage:', e); return []; } } }
    app = new TodoApp();
    expect(app.itemCount.textContent).toBe('No items');
    expect(app.todoList.innerHTML).toContain('No todos yet. Add one above!');
  });

  test('add button is disabled when input is empty', () => {
    class TodoApp { constructor() { this.todos = this.loadTodos(); this.todoInput = globalMock.document.getElementById('todoInput'); this.addBtn = globalMock.document.getElementById('addBtn'); this.todoList = globalMock.document.getElementById('todoList'); this.itemCount = globalMock.document.getElementById('itemCount'); this.emptyState = globalMock.document.getElementById('emptyState'); this.init(); } init() { this.addBtn.addEventListener('click', () => this.addTodo()); this.todoInput.addEventListener('keypress', (e) => { if (e.key === 'Enter') this.addTodo(); }); this.todoInput.addEventListener('input', () => this.updateAddButton()); this.render(); this.updateAddButton(); } addTodo() { const text = this.todoInput.value.trim(); if (!text) return; const todo = { id: Date.now() + Math.random(), text: text, completed: false, createdAt: new Date().toISOString() }; this.todos.push(todo); this.todoInput.value = ''; this.saveTodos(); this.render(); this.updateAddButton(); } toggleTodo(id) { const todo = this.todos.find(t => t.id === id); if (todo) { todo.completed = !todo.completed; this.saveTodos(); this.render(); } } deleteTodo(id) { this.todos = this.todos.filter(t => t.id !== id); this.saveTodos(); this.render(); } updateAddButton() { const hasText = this.todoInput.value.trim().length > 0; this.addBtn.disabled = !hasText; } render() { this.renderTodos(); this.updateItemCount(); } renderTodos() { if (this.todos.length === 0) { this.todoList.innerHTML = '<div class="empty-state">No todos yet. Add one above!</div>'; return; } const todosHtml = this.todos.map(todo => `<div class="todo-item ${todo.completed ? 'completed' : ''}"><input type="checkbox" class="todo-checkbox" ${todo.completed ? 'checked' : ''} onchange="app.toggleTodo(${todo.id})"><span class="todo-text">${this.escapeHtml(todo.text)}</span><button class="delete-btn" onclick="app.deleteTodo(${todo.id})">Delete</button></div>`).join(''); this.todoList.innerHTML = todosHtml; } updateItemCount() { const remaining = this.todos.filter(t => !t.completed).length; const total = this.todos.length; if (total === 0) { this.itemCount.textContent = 'No items'; } else if (remaining === 0) { this.itemCount.textContent = 'All items completed! 🎉'; } else { this.itemCount.textContent = `${remaining} item${remaining !== 1 ? 's' : ''} remaining`; } } escapeHtml(text) { const div = globalMock.document.createElement('div'); div.textContent = text; return div.innerHTML; } saveTodos() { try { globalMock.localStorage.setItem('todos', JSON.stringify(this.todos)); } catch (e) { globalMock.console.warn('Could not save todos to localStorage:', e); } } loadTodos() { try { const stored = globalMock.localStorage.getItem('todos'); return stored ? JSON.parse(stored) : []; } catch (e) { globalMock.console.warn('Could not load todos from localStorage:', e); return []; } } }
    app = new TodoApp();
    expect(app.addBtn.disabled).toBe(true);
  });

  test('add button is enabled when input has text', () => {
    class TodoApp { constructor() { this.todos = this.loadTodos(); this.todoInput = globalMock.document.getElementById('todoInput'); this.addBtn = globalMock.document.getElementById('addBtn'); this.todoList = globalMock.document.getElementById('todoList'); this.itemCount = globalMock.document.getElementById('itemCount'); this.emptyState = globalMock.document.getElementById('emptyState'); this.init(); } init() { this.addBtn.addEventListener('click', () => this.addTodo()); this.todoInput.addEventListener('keypress', (e) => { if (e.key === 'Enter') this.addTodo(); }); this.todoInput.addEventListener('input', () => this.updateAddButton()); this.render(); this.updateAddButton(); } addTodo() { const text = this.todoInput.value.trim(); if (!text) return; const todo = { id: Date.now() + Math.random(), text: text, completed: false, createdAt: new Date().toISOString() }; this.todos.push(todo); this.todoInput.value = ''; this.saveTodos(); this.render(); this.updateAddButton(); } toggleTodo(id) { const todo = this.todos.find(t => t.id === id); if (todo) { todo.completed = !todo.completed; this.saveTodos(); this.render(); } } deleteTodo(id) { this.todos = this.todos.filter(t => t.id !== id); this.saveTodos(); this.render(); } updateAddButton() { const hasText = this.todoInput.value.trim().length > 0; this.addBtn.disabled = !hasText; } render() { this.renderTodos(); this.updateItemCount(); } renderTodos() { if (this.todos.length === 0) { this.todoList.innerHTML = '<div class="empty-state">No todos yet. Add one above!</div>'; return; } const todosHtml = this.todos.map(todo => `<div class="todo-item ${todo.completed ? 'completed' : ''}"><input type="checkbox" class="todo-checkbox" ${todo.completed ? 'checked' : ''} onchange="app.toggleTodo(${todo.id})"><span class="todo-text">${this.escapeHtml(todo.text)}</span><button class="delete-btn" onclick="app.deleteTodo(${todo.id})">Delete</button></div>`).join(''); this.todoList.innerHTML = todosHtml; } updateItemCount() { const remaining = this.todos.filter(t => !t.completed).length; const total = this.todos.length; if (total === 0) { this.itemCount.textContent = 'No items'; } else if (remaining === 0) { this.itemCount.textContent = 'All items completed! 🎉'; } else { this.itemCount.textContent = `${remaining} item${remaining !== 1 ? 's' : ''} remaining`; } } escapeHtml(text) { const div = globalMock.document.createElement('div'); div.textContent = text; return div.innerHTML; } saveTodos() { try { globalMock.localStorage.setItem('todos', JSON.stringify(this.todos)); } catch (e) { globalMock.console.warn('Could not save todos to localStorage:', e); } } loadTodos() { try { const stored = globalMock.localStorage.getItem('todos'); return stored ? JSON.parse(stored) : []; } catch (e) { globalMock.console.warn('Could not load todos from localStorage